// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: shortener/v1/shortener.proto

package shortenerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // исходный URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`                 // сокращенный URL
	AlreadyExists bool                   `protobuf:"varint,2,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"` // true, если URL уже существует
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortenResponse) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

type ShortenBatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // ID элемента от клиента, чтобы сопоставить результат
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`       // Исходный URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchItem) Reset() {
	*x = ShortenBatchItem{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchItem) ProtoMessage() {}

func (x *ShortenBatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchItem.ProtoReflect.Descriptor instead.
func (*ShortenBatchItem) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenBatchItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ShortenBatchItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // список URL на вход
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest) Reset() {
	*x = ShortenBatchRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest) ProtoMessage() {}

func (x *ShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenBatchRequest) GetItems() []*ShortenBatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShortenBatchResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"` // только URL, без short_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponseItem) Reset() {
	*x = ShortenBatchResponseItem{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponseItem) ProtoMessage() {}

func (x *ShortenBatchResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponseItem.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponseItem) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *ShortenBatchResponseItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchResponseItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortenBatchResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*ShortenBatchResponseItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // список результатов в том же порядке, что и вход
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse) Reset() {
	*x = ShortenBatchResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse) ProtoMessage() {}

func (x *ShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *ShortenBatchResponse) GetItems() []*ShortenBatchResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortId       string                 `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectRequest) Reset() {
	*x = RedirectRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectRequest) ProtoMessage() {}

func (x *RedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectRequest.ProtoReflect.Descriptor instead.
func (*RedirectRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *RedirectRequest) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

type RedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectResponse) Reset() {
	*x = RedirectResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResponse) ProtoMessage() {}

func (x *RedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResponse.ProtoReflect.Descriptor instead.
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *RedirectResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ListUserURLsResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserURLsResponseItem) Reset() {
	*x = ListUserURLsResponseItem{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserURLsResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserURLsResponseItem) ProtoMessage() {}

func (x *ListUserURLsResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserURLsResponseItem.ProtoReflect.Descriptor instead.
func (*ListUserURLsResponseItem) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserURLsResponseItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ListUserURLsResponseItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ListUserURLsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*ListUserURLsResponseItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // список пар URLs на выход
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserURLsResponse) Reset() {
	*x = ListUserURLsResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserURLsResponse) ProtoMessage() {}

func (x *ListUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserURLsResponse.ProtoReflect.Descriptor instead.
func (*ListUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserURLsResponse) GetItems() []*ListUserURLsResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrls     []string               `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserURLsRequest) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *StatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_shortener_v1_shortener_proto protoreflect.FileDescriptor

const file_shortener_v1_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1cshortener/v1/shortener.proto\x12\fshortener.v1\x1a\x1bgoogle/protobuf/empty.proto\"3\n" +
	"\x0eShortenRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"U\n" +
	"\x0fShortenResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12%\n" +
	"\x0ealready_exists\x18\x02 \x01(\bR\ralreadyExists\"\\\n" +
	"\x10ShortenBatchItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"K\n" +
	"\x13ShortenBatchRequest\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.shortener.v1.ShortenBatchItemR\x05items\"^\n" +
	"\x18ShortenBatchResponseItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"T\n" +
	"\x14ShortenBatchResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.shortener.v1.ShortenBatchResponseItemR\x05items\",\n" +
	"\x0fRedirectRequest\x12\x19\n" +
	"\bshort_id\x18\x01 \x01(\tR\ashortId\"5\n" +
	"\x10RedirectResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"Z\n" +
	"\x18ListUserURLsResponseItem\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"T\n" +
	"\x14ListUserURLsResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.shortener.v1.ListUserURLsResponseItemR\x05items\"6\n" +
	"\x15DeleteUserURLsRequest\x12\x1d\n" +
	"\n" +
	"short_urls\x18\x01 \x03(\tR\tshortUrls\"9\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users2\x8d\x04\n" +
	"\x10ShortenerService\x12F\n" +
	"\aShorten\x12\x1c.shortener.v1.ShortenRequest\x1a\x1d.shortener.v1.ShortenResponse\x12U\n" +
	"\fShortenBatch\x12!.shortener.v1.ShortenBatchRequest\x1a\".shortener.v1.ShortenBatchResponse\x12I\n" +
	"\bRedirect\x12\x1d.shortener.v1.RedirectRequest\x1a\x1e.shortener.v1.RedirectResponse\x12J\n" +
	"\fListUserURLs\x12\x16.google.protobuf.Empty\x1a\".shortener.v1.ListUserURLsResponse\x12M\n" +
	"\x0eDeleteUserURLs\x12#.shortener.v1.DeleteUserURLsRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\x05Stats\x12\x16.google.protobuf.Empty\x1a\x1b.shortener.v1.StatsResponseB[ZYgithub.com/NailUsmanov/practicum-shortener-url/internal/genproto/shortener/v1;shortenerpbb\x06proto3"

var (
	file_shortener_v1_shortener_proto_rawDescOnce sync.Once
	file_shortener_v1_shortener_proto_rawDescData []byte
)

func file_shortener_v1_shortener_proto_rawDescGZIP() []byte {
	file_shortener_v1_shortener_proto_rawDescOnce.Do(func() {
		file_shortener_v1_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_v1_shortener_proto_rawDesc), len(file_shortener_v1_shortener_proto_rawDesc)))
	})
	return file_shortener_v1_shortener_proto_rawDescData
}

var file_shortener_v1_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_shortener_v1_shortener_proto_goTypes = []any{
	(*ShortenRequest)(nil),           // 0: shortener.v1.ShortenRequest
	(*ShortenResponse)(nil),          // 1: shortener.v1.ShortenResponse
	(*ShortenBatchItem)(nil),         // 2: shortener.v1.ShortenBatchItem
	(*ShortenBatchRequest)(nil),      // 3: shortener.v1.ShortenBatchRequest
	(*ShortenBatchResponseItem)(nil), // 4: shortener.v1.ShortenBatchResponseItem
	(*ShortenBatchResponse)(nil),     // 5: shortener.v1.ShortenBatchResponse
	(*RedirectRequest)(nil),          // 6: shortener.v1.RedirectRequest
	(*RedirectResponse)(nil),         // 7: shortener.v1.RedirectResponse
	(*ListUserURLsResponseItem)(nil), // 8: shortener.v1.ListUserURLsResponseItem
	(*ListUserURLsResponse)(nil),     // 9: shortener.v1.ListUserURLsResponse
	(*DeleteUserURLsRequest)(nil),    // 10: shortener.v1.DeleteUserURLsRequest
	(*StatsResponse)(nil),            // 11: shortener.v1.StatsResponse
	(*emptypb.Empty)(nil),            // 12: google.protobuf.Empty
}
var file_shortener_v1_shortener_proto_depIdxs = []int32{
	2,  // 0: shortener.v1.ShortenBatchRequest.items:type_name -> shortener.v1.ShortenBatchItem
	4,  // 1: shortener.v1.ShortenBatchResponse.items:type_name -> shortener.v1.ShortenBatchResponseItem
	8,  // 2: shortener.v1.ListUserURLsResponse.items:type_name -> shortener.v1.ListUserURLsResponseItem
	0,  // 3: shortener.v1.ShortenerService.Shorten:input_type -> shortener.v1.ShortenRequest
	3,  // 4: shortener.v1.ShortenerService.ShortenBatch:input_type -> shortener.v1.ShortenBatchRequest
	6,  // 5: shortener.v1.ShortenerService.Redirect:input_type -> shortener.v1.RedirectRequest
	12, // 6: shortener.v1.ShortenerService.ListUserURLs:input_type -> google.protobuf.Empty
	10, // 7: shortener.v1.ShortenerService.DeleteUserURLs:input_type -> shortener.v1.DeleteUserURLsRequest
	12, // 8: shortener.v1.ShortenerService.Ping:input_type -> google.protobuf.Empty
	12, // 9: shortener.v1.ShortenerService.Stats:input_type -> google.protobuf.Empty
	1,  // 10: shortener.v1.ShortenerService.Shorten:output_type -> shortener.v1.ShortenResponse
	5,  // 11: shortener.v1.ShortenerService.ShortenBatch:output_type -> shortener.v1.ShortenBatchResponse
	7,  // 12: shortener.v1.ShortenerService.Redirect:output_type -> shortener.v1.RedirectResponse
	9,  // 13: shortener.v1.ShortenerService.ListUserURLs:output_type -> shortener.v1.ListUserURLsResponse
	12, // 14: shortener.v1.ShortenerService.DeleteUserURLs:output_type -> google.protobuf.Empty
	12, // 15: shortener.v1.ShortenerService.Ping:output_type -> google.protobuf.Empty
	11, // 16: shortener.v1.ShortenerService.Stats:output_type -> shortener.v1.StatsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_shortener_v1_shortener_proto_init() }
func file_shortener_v1_shortener_proto_init() {
	if File_shortener_v1_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_v1_shortener_proto_rawDesc), len(file_shortener_v1_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortener_v1_shortener_proto_goTypes,
		DependencyIndexes: file_shortener_v1_shortener_proto_depIdxs,
		MessageInfos:      file_shortener_v1_shortener_proto_msgTypes,
	}.Build()
	File_shortener_v1_shortener_proto = out.File
	file_shortener_v1_shortener_proto_goTypes = nil
	file_shortener_v1_shortener_proto_depIdxs = nil
}
